swiftlint_version: 0.31.0
disabled_rules:
  - closing_brace
  - opening_brace
  - identifier_name
  - type_name
  - trailing_whitespace
  - nesting
  - todo
  - force_cast
  - force_try

excluded:
  - Carthage
  - scripts
  - DataTests
  - DomainTests
  - PresentationTests
  - SupportTests

trailing_whitespace:
  severity: error

line_length:
  warning: 200
  error: 200

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200

trailing_comma:
  mandatory_comma: true